<a href="https://colab.research.google.com/github/mljittery/MangLian_DTSC3020_Summer2026/blob/main/Copy_of_Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 6 — File Handling, Data Processing, and Calculation

**Course:** DTSC 3020 — Introduction to Computation with Python  
**Covers:** Lesson 6 — file I/O, the `os`, `shutil`, and `csv` modules, NumPy arrays, and pandas DataFrames  
**Points:** 50 (5 problems, 10 points each)  
**Released:** Monday, July 6, 2026  
**Due:** Friday, July 10, 2026, at 11:59 PM CT

---

## Before you start

1. Make your own copy: **File → Save a copy in Drive**.
2. Rename the notebook using your last name first, for example: `SmithAssignment6.ipynb`.
3. In each answer cell, replace `Your Name` with your full name.

## Rules

- Use **meaningful variable names** and consistent indentation.
- Complete the problems in order. This notebook is self-contained: all required files are created by your code, but **Problem 2 uses the file created in Problem 1**.
- Do **not** manually upload any data files.
- Do **not hard-code** expected totals, counts, statistics, or filtered results. Calculate them from the provided data.
- Equivalent correct solutions are accepted unless a problem requires a specific function or method.
- Before submitting, select **Runtime → Restart and run all**. Every cell must run without errors from top to bottom.
- After running all cells, **save the notebook again** so that your outputs are visible in the submitted GitHub file.

## Grading

| Problem | Skill focus | Points |
|---|---|---:|
| 1 | Write, locate, and read a text file | 10 |
| 2 | Rename and copy a file safely | 10 |
| 3 | Write and read CSV data and calculate a total | 10 |
| 4 | Create and calculate with a NumPy array | 10 |
| 5 | Save, load, summarize, and filter data with pandas | 10 |

Each problem is generally graded as follows:

- **7 points:** correct code and logic
- **1 point:** required output and formatting
- **1 point:** conceptual comment
- **1 point:** readability and successful execution

## Submission

Push the completed notebook to GitHub using **File → Save a copy in GitHub**, then paste the GitHub URL in Canvas.


---


## Problem 1 — Write and Read a Text File *(10 points)*

Create a text file with Python, confirm that it exists, and read its contents.

### What to do

1. Import the `os` module.
2. Using a `with open(...)` block in **write mode** (`"w"`), create a file named `shop_notes.txt` containing exactly these three lines:

   ```text
   Eagle Beans daily log
   Lattes sold: 42
   Muffins sold: 17
   ```

   Add `"\n"` after each line so that the lines are stored separately. Use `encoding="utf-8"` when opening the file.
3. Use `os.path.exists("shop_notes.txt")` to confirm that the file exists and print the result.
4. Open the file in **read mode** (`"r"`) and print its full contents.
5. Open it once more, use `.readlines()` to count the lines, and print:

   ```text
   Line count: 3
   ```

6. Add a one-sentence **comment** explaining why `with open(...)` is preferred over manually calling `open()` and `close()`.

### Hints

- Write mode (`"w"`) creates a new file or overwrites an existing file.
- Read mode (`"r"`) reads an existing file.
- `os.path.exists(path)` returns `True` or `False`.
- `.read()` returns the entire file as one string.
- `.readlines()` returns a list in which each item represents one line.


In [9]:
# Mang Lian — Problem 1

import os

with open("shop_notes.txt", "w", encoding="utf-8") as file:
  file.write("Eagle Beans daily log\n")
  file.write("Lattes sold: 42\n")
  file.write("Muffins sold: 17\n")

file_exists = os.path.exists("shop_notes.txt")
print("File exists:", file_exists)

with open("shop_notes.txt", "r", encoding="utf-8") as file:
  contents = file.read()
  print(contents)

with open("shop_notes.txt", "r", encoding="utf-8") as file:
  lines = file.readlines()
  line_count = len(lines)
  print("Line count:", line_count)

# open(...) auto closes file for you, even if error happen.


File exists: True
Eagle Beans daily log
Lattes sold: 42
Muffins sold: 17

Line count: 3


## Problem 2 — Rename and Copy a File *(10 points)*

Rename the file created in Problem 1 and make a backup copy. **Run Problem 1 before this problem.**

### What to do

1. Import `os` and `shutil`.
2. Use `os.rename(...)` to rename `shop_notes.txt` as `shop_log.txt`.
3. Use `os.path.exists(...)` to print the following checks:

   ```text
   Old name exists? False
   New name exists? True
   ```

4. Use `shutil.copy(...)` to create a backup named `shop_log_backup.txt`.
5. Print whether the backup exists.
6. Use `os.listdir(".")` to obtain the current folder contents. From that result, print the filenames `shop_log.txt` and `shop_log_backup.txt` so the grader can confirm that both exist. Other files in the folder do not need to be printed.
7. Add a one-sentence **comment** explaining the difference between renaming a file and copying a file.

### Hints

- `os.rename(old_name, new_name)` changes the filename; the old filename no longer remains.
- `shutil.copy(source, destination)` keeps the source file and creates a duplicate.
- `os.listdir(".")` returns the contents of the current folder.
- The order returned by `os.listdir(...)` is not guaranteed, so do not depend on a particular order.


In [10]:
# Mang Lian — Problem 2

import os
import shutil

os.rename("shop_notes.txt", "shop_log.txt")

print("Old name exists?", os.path.exists("shop_notes.txt"))
print("New name exists?", os.path.exists("shop_log.txt"))

shutil.copy("shop_log.txt", "shop_log_backup.txt")
print("Backup exists?", os.path.exists("shop_log_backup.txt"))

folder_contents = os.listdir(".")
for item in folder_contents:
  if item == "shop_log.txt" or item == "shop_log_backup.txt":
    print(item)

# Renaming file changes name and old name no longer exists, while
# copying file keeps the original and create new duplicate file.


Old name exists? False
New name exists? True
Backup exists? True
shop_log.txt
shop_log_backup.txt


## Problem 3 — Work with a CSV File *(10 points)*

Write tabular data to a CSV file, read it back, and calculate total sales.

### What to do

1. Import the `csv` module.
2. Using `csv.writer`, create a file named `sales.csv` with the following header and data rows:

   ```text
   item,qty,price
   latte,3,4.50
   muffin,2,3.25
   mocha,1,5.00
   ```

   Open the file with `newline=""` and `encoding="utf-8"` when writing.
3. Open `sales.csv` with `csv.reader`.
4. Read and store the header using `next(reader)`.
5. Loop through the remaining rows and calculate:

   ```text
   total_sales = sum of (quantity × price) for all rows
   ```

   CSV values are read as strings, so convert quantity with `int(...)` and price with `float(...)`.
6. Print the header and print the total formatted as money:

   ```text
   Total sales: $25.00
   ```

7. Add a one-sentence **comment** explaining why CSV values must be converted before performing numerical calculations.

### Hints

- `writer.writerows(rows)` writes multiple rows.
- `next(reader)` reads the next row and moves the reader forward.
- `int("3") * float("4.50")` performs numerical multiplication.
- Do not directly print `$25.00`; calculate the total from the rows.


In [4]:
# Mang Lian — Problem 3

import csv

header = ["item", "qty", "price"]
data = [
    ["latte", 3, 4.50],
    ["muffin", 2, 3.25],
    ["mocha", 1, 5.00]
]

with open("sales.csv", "w", newline="", encoding="utf-8") as file:
  writer = csv.writer(file)
  writer.writerow(header)
  writer.writerows(data)

with open("sales.csv", "r", newline="", encoding="utf-8") as file:
  reader = csv.reader(file)
  header = next(reader)

  total_sales = 0
  for row in reader:
    item, qty, price = row
    total_sales += int(qty) * float(price)

print(header)
print("Total sales: ${:.2f}".format(total_sales))

# CSV files store every value as plain text, so numbers
# must be convert with int or float before can be use in math.


['item', 'qty', 'price']
Total sales: $25.00


## Problem 4 — Calculations with NumPy *(10 points)*

Use a NumPy array to perform numerical calculations without writing loops.

### What to do

1. Import NumPy using the standard alias: `import numpy as np`.
2. Create the following NumPy array of daily high temperatures in degrees Fahrenheit:

   ```python
   temps = np.array([68, 72, 70, 74, 69, 73, 71])
   ```

3. Print each result with a clear label:

   - mean: `71.0`
   - maximum: `74`
   - minimum: `68`
   - population standard deviation, rounded to two decimal places: `2.0`

4. Use **Boolean indexing** to select temperatures greater than 71. Print the selected values and their count.

   Expected values:

   ```text
   [72 74 73]
   Count: 3
   ```

5. Use one **vectorized expression** to convert all Fahrenheit values to Celsius:

   ```text
   Celsius = (Fahrenheit - 32) × 5 / 9
   ```

   Round the resulting array to one decimal place and print it. Do not use a loop.

   Expected result:

   ```text
   [20.  22.2 21.1 23.3 20.6 22.8 21.7]
   ```

6. Add a one-sentence **comment** naming one advantage of a NumPy array over a Python list for numerical work.

### Hints

- `np.array([...])` creates a NumPy array.
- You may use either NumPy functions, such as `np.mean(temps)`, or equivalent array methods, such as `temps.mean()`.
- `temps > 71` creates a Boolean array.
- `temps[temps > 71]` keeps only values whose Boolean positions are `True`.
- `np.round(array, 1)` rounds each element to one decimal place.


In [11]:
# Mang Lian — Problem 4

import numpy as np

temps = np.array([68, 72, 70, 74, 69, 73, 71])

print("Mean:", np.mean(temps))
print("Maximum:", np.max(temps))
print("Minimum:", np.min(temps))
print("Population standard deviation:", np.std(temps).round(2))

warm_temps = temps[temps > 71]
print(warm_temps)
print("Count:", len(warm_temps))

celsius = (temps - 32) * 5 / 9
print(np.round(celsius, 1))

# A NumPy array does math on every element at once without needing manual for
# loop like Python list would

Mean: 71.0
Maximum: 74
Minimum: 68
Population standard deviation: 2.0
[72 74 73]
Count: 3
[20.  22.2 21.1 23.3 20.6 22.8 21.7]


## Problem 5 — Save, Load, and Analyze Data with pandas *(10 points)*

Create a pandas DataFrame, save it as a CSV file, load it again, and answer questions about the data.

### What to do

1. Import pandas using the standard alias: `import pandas as pd`.
2. Create a DataFrame from the following dictionary:

   ```python
   data = {
       "name":  ["Maria", "Devon", "Aisha", "Carlos", "Lena"],
       "drink": ["latte", "mocha", "latte", "espresso", "mocha"],
       "spent": [12.50, 9.00, 15.25, 4.50, 9.00],
   }
   ```

3. Store the first DataFrame in a meaningfully named variable such as `customer_data`.
4. Save it as `customers.csv` using `.to_csv(..., index=False)`.
5. Load `customers.csv` with `pd.read_csv(...)` and store the loaded DataFrame in `df`.
6. Print the complete loaded DataFrame.
7. Print each result with a clear label:

   - shape: `(5, 3)`
   - total spent: `$50.25`
   - average spent, rounded to two decimal places: `$10.05`

8. Filter `df` to show only the `name` and `spent` columns for customers who spent **more than $10**. The result should contain Maria and Aisha.
9. Use `df["drink"].value_counts()` to print the number of customers who ordered each drink.
10. Add a one-sentence **comment** explaining the difference between a pandas DataFrame and a pandas Series.

### Hints

- `pd.DataFrame(data)` creates a table from a dictionary.
- `df.to_csv("customers.csv", index=False)` prevents pandas from saving an extra index column.
- `pd.read_csv("customers.csv")` loads a CSV file as a DataFrame.
- `df[df["spent"] > 10][["name", "spent"]]` filters rows and selects columns.
- `value_counts()` may display categories with equal counts in a different order. Correct counts matter more than order.


In [12]:
# Mang Lian — Problem 5

import pandas as pd

data = {
    "name":  ["Maria", "Devon", "Aisha", "Carlos", "Lena"],
    "drink": ["latte", "mocha", "latte", "espresso", "mocha"],
    "spent": [12.50, 9.00, 15.25, 4.50, 9.00],
}

customer_data = pd.DataFrame(data)
customer_data.to_csv("customers.csv", index=False)

df = pd.read_csv("customers.csv")
print(df)

print("Shape:", df.shape)

total_spent = df["spent"].sum()
average_spent = df["spent"].mean()
print("Total spent: $" + format(total_spent, ".2f"))
print("Average spent: $" + format(average_spent, ".2f"))

high_spenders = df[df["spent"] > 10][["name", "spent"]]
print(high_spenders)

print(df["drink"].value_counts())

# A dataframe is full table with rows and muliple named columns,
# A series is a single column or row of labeled data.

     name     drink  spent
0   Maria     latte  12.50
1   Devon     mocha   9.00
2   Aisha     latte  15.25
3  Carlos  espresso   4.50
4    Lena     mocha   9.00
Shape: (5, 3)
Total spent: $50.25
Average spent: $10.05
    name  spent
0  Maria  12.50
2  Aisha  15.25
drink
latte       2
mocha       2
espresso    1
Name: count, dtype: int64
